name = "w3clock"
main = "dist/worker.mjs"
compatibility_date = "2023-02-28"

[build]
command = "npm run build:worker:debug"

[durable_objects]
bindings = [
  { name = "CLOCK", class_name = "DurableClock0" }
]

[[migrations]]
tag = "v1"
new_classes = ["DurableClock0"]

# Production!
[env.production]
workers_dev = false
account_id = "fffa4b4363a7e5250af8357087263b3a"

[env.production.build]
command = "npm run build"

[env.production.vars]
DID = "did:web:clock.web3.storage"

[env.production.durable_objects]
bindings = [
  { name = "CLOCK", class_name = "DurableClock0" }
]

# Staging!
[env.staging]
workers_dev = false
account_id = "fffa4b4363a7e5250af8357087263b3a"

[env.staging.build]
command = "npm run build"

[env.staging.vars]
DID = "did:web:clock-staging.web3.storage"

[env.staging.durable_objects]
bindings = [
  { name = "CLOCK", class_name = "DurableClock0" }
]

# Test!
[env.test]
workers_dev = true

[env.test.vars]
DEBUG = "true"

# Developers Developers Developers!

[env.alanshaw]
workers_dev = true
account_id = "4fe12d085474d33bdcfd8e9bed4d8f95"

[env.alanshaw.vars]
DEBUG = "true"
